spring.application.name=warehousemanagement
server.address=0.0.0.0
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=PostgreSQL-DellG3
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/wm?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL-DellG3
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.messages.basename=messages
spring.web.locale-resolver=fixed
spring.web.locale=en

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true